# Generated by Django 4.2.29 on 2026-03-15 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Titre")),
                ("slug", models.SlugField(unique=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("it", "Projet IT"),
                            ("entrepreneurial", "Entrepreneurial"),
                            ("startup", "Accompagnement Startup"),
                            ("freelance", "Freelance"),
                        ],
                        max_length=50,
                        verbose_name="Catégorie",
                    ),
                ),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "technologies",
                    models.CharField(
                        help_text="Séparées par des virgules",
                        max_length=500,
                        verbose_name="Technologies utilisées",
                    ),
                ),
                ("objectives", models.TextField(verbose_name="Objectifs")),
                ("results", models.TextField(verbose_name="Résultats")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="projects/",
                        verbose_name="Image",
                    ),
                ),
                (
                    "featured",
                    models.BooleanField(default=False, verbose_name="Mis en avant"),
                ),
                (
                    "link",
                    models.URLField(
                        blank=True, null=True, verbose_name="Lien du projet"
                    ),
                ),
                (
                    "github",
                    models.URLField(blank=True, null=True, verbose_name="Lien GitHub"),
                ),
                ("created_at", models.DateField(auto_now_add=True)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Projet",
                "verbose_name_plural": "Projets",
                "ordering": ["order", "-created_at"],
            },
        ),
    ]
