# Generated by Django 4.2.29 on 2026-03-15 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="features",
            field=models.TextField(
                blank=True, verbose_name="Fonctionnalités principales de la plateforme"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="impact",
            field=models.TextField(blank=True, verbose_name="Impact du projet"),
        ),
    ]
