# Generated by Django 4.2.29 on 2026-03-16 00:04

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_project_features_project_impact"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="features",
            field=ckeditor.fields.RichTextField(
                blank=True, verbose_name="Fonctionnalités principales de la plateforme"
            ),
        ),
    ]
