# Generated by Django 4.2.29 on 2026-03-15 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Experience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Poste")),
                (
                    "company",
                    models.CharField(max_length=200, verbose_name="Entreprise"),
                ),
                (
                    "location",
                    models.CharField(blank=True, max_length=100, verbose_name="Lieu"),
                ),
                ("start_date", models.DateField(verbose_name="Date de début")),
                (
                    "end_date",
                    models.DateField(blank=True, null=True, verbose_name="Date de fin"),
                ),
                (
                    "is_current",
                    models.BooleanField(default=False, verbose_name="Poste actuel"),
                ),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "missions",
                    models.TextField(
                        help_text="Une mission par ligne",
                        verbose_name="Missions principales",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Expérience",
                "verbose_name_plural": "Expériences",
                "ordering": ["order", "-start_date"],
            },
        ),
    ]
